version: "3.9"
services:
  db:
    image: postgres
    container_name: postgres_db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=houses_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/postgres/raw_data/house_prices.csv:/postgres/raw_data/house_prices.csv
  spark-master:
    image: bitnami/spark
    container_name: spark_master
    ports:
      - "7077:7077"
    volumes:
      - ./app/main.py:/opt/bitnami/spark/main.py
      - ./app/drivers/postgresql-jdbc.jar:/opt/bitnami/spark/jars/postgresql-jdbc.jar
  spark-worker-1:
    image: bitnami/spark
    container_name: spark_worker_1
    environment:
      - SPARK_MODE=worker
  spark-worker-2:
      image: bitnami/spark
      container_name: spark_worker_2
      environment:
        - SPARK_MODE=worker

